### ISSUE TITLE
extraction of many reviews > 1500 fails

### ISSUE THREAD

**Issue by panoptikum** [drawrowfly/amazon-product-api#20]
If I run:

`amazon-buddy reviews B071W8R4PS --country DE -n 2000`

I get the following error:
```

ReferenceError: reject is not defined
    at AmazonScraper.startScraper (/home/felix/anaconda3/lib/node_modules/amazon-buddy/lib/Amazon.js:145:116)
    at Object.exports.reviews (/home/felix/anaconda3/lib/node_modules/amazon-buddy/lib/index.js:43:55)
    at startScraper (/home/felix/anaconda3/lib/node_modules/amazon-buddy/bin/cli.js:8:58)
    at Object.require.usage.example.example.example.example.example.example.command.command [as handler] (/home/felix/anaconda3/lib/node_modules/amazon-buddy/bin/cli.js:47:9)
    at Object.runCommand (/home/felix/anaconda3/lib/node_modules/amazon-buddy/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/home/felix/anaconda3/lib/node_modules/amazon-buddy/node_modules/yargs/yargs.js:1105:41)
    at Object.get [as argv] (/home/felix/anaconda3/lib/node_modules/amazon-buddy/node_modules/yargs/yargs.js:1033:21)
    at Object.<anonymous> (/home/felix/anaconda3/lib/node_modules/amazon-buddy/bin/cli.js:187:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

```

Any ideas what's going wrong?

**Comment by drawrowfly** [comment]
update the app
